### PR TITLE
Support Netflow v9

### PR DESCRIPTION
**Pull request by bhklimk**
All

Summary: here is an adapted plugin that supports Netflow v9.  In essence, the major changes are 
- a singleton object that defines the title and lengths from the most common v9 fields
- logic that can parse out the template records from a v9 device in order to process a v9 data record.

Once compiled, all you have to do is drop the jar file into the appropriate folder.  

Background: I developed it for an undergraduate cyber defense exercise so my students could monitor their Cisco ASA firewall.  Over the period of two weeks the modified plugin was used successfully with no issues.  Unfortunately, other responsibilities had kept me from posting the code until today (about 2 months after the competition).  If there are any recommendations or comments to make this code better please let me know.  If there is a strong desire for IPFIX support, I can modify the singleton to capture that traffic as well.

=="Ben Klim"

Refs #1

### CODE REVIEW

**Comment by bhklimk** [comment]
Had some small formatting issues but everything should be fixed now.  Please let me know if the language or formatting of the licenses needed to massaged.

**Comment by joschi** [comment]
@bhklimk Thank you for your contribution to Graylog!

Before we can accept any code from you, we need you to sign our [Contributor License Agreement](https://s3.amazonaws.com/graylog2public/Individual+Contributor+Assignment+Agreement+-+Graylog.pdf). Please send us a signed copy to hello@graylog.com so we can merge your pull request.

This is only required once, no matter how many contributions you make in the future. Thank you for helping us with this unfortunate administrative requirement!

**Comment by bhklimk** [comment]
No worries; signed and emailed it out this morning!

**Comment by lennartkoopmann** [comment]
I confirm that we have received the CLA! Thank you so much for your contribution.

**Comment by bernd** [comment]
Thanks again for the PR! :smiley: Testing and reviewing this will take me some time because I am currently busy with other things.

In the meantime it would be great if you could remove the editor backup files you committed. (all files that end in `*~`) We do not commit those files. :smiley: Thanks!

**Comment by bhklimk** [comment]
@bernd backup files removed!

**Comment by mholttech** [comment]
is there a compiled version of this I can use for testing?

**Comment by bernd** [comment]
@mholttech I uploaded a compiled version of this. Happy testing! :smiley: 

https://s3.amazonaws.com/graylog2public/plugins/graylog-plugin-netflow-0.1.2-SNAPSHOT-v9.jar

**Comment by taishan69** [comment]
**@bernd** I'm currently testing the netflow plugin in the latest Graylog beta (deployed within the OVA appliance, Graylog 2.1.0-beta.2+ffa3355 on graylog (Oracle Corporation 1.8.0_101 on Linux 4.2.0-41-generic)), and I'm getting leading forward slashes in the IPV4_SRC_ADDR and IPV4_DST_ADDR fields.  Device exporting netflow is a Cisco Meraki MX64.

**Comment by digger-squared** [comment]
Both IPV4_DST_ADDR and IPV4_SRC_ADDR have a leading "/" in front of the IP address.

for example

IPV4_DST_ADDR
/8.8.8.8

**Comment by f0o** [comment]
Hi,

Awesome work on the v9 support!

I've added the plugin and restarted graylog and added a NetFlow Input. However despite seeing traffic on the input (see below) I dont see any messages being recorded. What am I missing?

```
Throughput / Metrics
1 minute average rate: 1 msg/s
Network IO: 164.0B 0B (total: 10.8KB 0B )
Empty messages discarded: 0
```

**Comment by lennartkoopmann** [comment]
I just tested it with Meraki gear and it works great. Definitely needs some improvements that I might tackle soon. Thanks already!

**Pull request closed without merging**
